version: '3.8'
services:
  mydb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: sushkof
    volumes:
      - ./static/init.sql:/docker-entrypoint-initdb.d/init_db.sql

    ports:
      - "3306:3306"
        
  app:
    build: .
    ports:
      - "9080:9080"
    depends_on:
      - mydb
    command: sh -c "sleep 20  && ./main -h mydb"
